### ISSUE TITLE
Check that the length of principals in CDPs is limited to length 1

### ISSUE THREAD

**Issue by jmahess** [Kava-Labs/kava#457] opened 2020-04-22 20:59 UTC
@karzak fyi

**Comment by denalimarsh** [comment] 2020-04-22 21:22
Why is this check required? It looks like the intended behavior of cdp module's `ValidatePrincipalAdd` is to iterate all principal coins and validate each one individually but not to limit the number of principal coins.

**Comment by karzak** [comment] 2020-04-28 17:44
closed via #466

**Closed** 2020-04-28 17:43 UTC
